#!/usr/bin/env node
/**
 * Regenerates the "BLOG_POSTS" block in public/sitemap.xml from
 * src/data/posts.ts, leaving every other sitemap entry untouched.
 *
 * Runs automatically before every `npm run build` (see "prebuild" in
 * package.json). Can also be run manually: `npm run sitemap`.
 *
 * Implementation note: this parses posts.ts with regex instead of
 * importing it, since the project has no TypeScript-executing runtime
 * (e.g. tsx/ts-node) installed and we want to keep the build fast and
 * dependency-free. This relies on the `slug` and `lastmod` fields each
 * appearing exactly once per post object, in the same relative order.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const POSTS_FILE = path.join(ROOT, "src/data/posts.ts");
const SITEMAP_FILE = path.join(ROOT, "public/sitemap.xml");
const SITE_ORIGIN = "https://www.orachope.org";

const START_MARKER = "<!-- BLOG_POSTS:START (auto-generated by scripts/generate-sitemap.mjs, do not edit by hand) -->";
const END_MARKER = "<!-- BLOG_POSTS:END -->";

function escapeRegExp(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function extractPosts(source) {
  const slugs = [...source.matchAll(/slug:\s*"([^"]+)"/g)].map((m) => m[1]);
  const lastmods = [...source.matchAll(/lastmod:\s*"([^"]+)"/g)].map((m) => m[1]);

  if (slugs.length === 0) {
    throw new Error("generate-sitemap: no posts found in src/data/posts.ts (no `slug` fields matched).");
  }

  if (slugs.length !== lastmods.length) {
    throw new Error(
      `generate-sitemap: found ${slugs.length} "slug" field(s) but ${lastmods.length} "lastmod" field(s) in posts.ts — check field order/formatting.`
    );
  }

  return slugs.map((slug, i) => ({ slug, lastmod: lastmods[i] }));
}

function buildBlogBlock(posts) {
  const today = new Date().toISOString().slice(0, 10);
  const lines = [START_MARKER];

  lines.push(
    "  <url>",
    `    <loc>${SITE_ORIGIN}/blog</loc>`,
    `    <lastmod>${today}</lastmod>`,
    "    <changefreq>weekly</changefreq>",
    "    <priority>0.7</priority>",
    "  </url>"
  );

  for (const post of posts) {
    lines.push(
      "  <url>",
      `    <loc>${SITE_ORIGIN}/blog/${post.slug}</loc>`,
      `    <lastmod>${post.lastmod}</lastmod>`,
      "    <changefreq>monthly</changefreq>",
      "    <priority>0.6</priority>",
      "  </url>"
    );
  }

  lines.push(END_MARKER);
  return lines.join("\n");
}

function main() {
  const postsSource = readFileSync(POSTS_FILE, "utf8");
  const posts = extractPosts(postsSource);
  const blogBlock = buildBlogBlock(posts);

  const sitemap = readFileSync(SITEMAP_FILE, "utf8");
  const blockPattern = new RegExp(`${escapeRegExp(START_MARKER)}[\\s\\S]*?${escapeRegExp(END_MARKER)}`);

  if (!blockPattern.test(sitemap)) {
    throw new Error(
      `generate-sitemap: could not find the "${START_MARKER}" ... "${END_MARKER}" markers in public/sitemap.xml.`
    );
  }

  const updatedSitemap = sitemap.replace(blockPattern, blogBlock);
  writeFileSync(SITEMAP_FILE, updatedSitemap, "utf8");
  console.log(`generate-sitemap: wrote ${posts.length} blog post URL(s) to public/sitemap.xml`);
}

main();
