name: Mirror to Borderless-med Front-end

on:
  push:
    branches:
      - main # IMPORTANT: Change this if your main branch is not called 'main'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Mirror Push
        run: |
          git remote add mirror git@github.com:Borderless-med/UX-Front-end.git
          git push --mirror mirror